apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sky
  template:
    metadata:
      labels:
        app: sky
    spec:
      containers:
      - image: okteto.dev/sky:latest
        name: sky
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "273bcebd-5ad0-401e-ac62-7ccf985162ee"
        - name: Vless_Path
          value: "/vless"
        - name: Vmess_UUID
          value: "273bcebd-5ad0-401e-ac62-7ccf985162ee"
        - name: Vmess_Path
          value: "/vmess"
        - name: Share_Path
          value: "/v2link"
