apiVersion: apps/v1
kind: Deployment
metadata:
  name: zxqc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zxqc
  template:
    metadata:
      labels:
        app: zxqc
    spec:
      containers:
      - image: okteto.dev/zxqc:latest
        name: zxqc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/BrainStorm-html.zip"
        - name: Vless_UUID
          value: "f0cd3ad2-e2ba-440a-898e-028e8f4627e5"
        - name: Vless_Path
          value: "/vless"
        - name: Vmess_UUID
          value: "f0cd3ad2-e2ba-440a-898e-028e8f4627e5"
        - name: Vmess_Path
          value: "/vmess"
        - name: Share_Path
          value: "/v2link"
